export const galleryItems = [
  { image: "/gallery/optimized/gallery-01.webp", text: "" },
  { image: "/gallery/optimized/gallery-02.webp", text: "" },
  { image: "/gallery/optimized/gallery-03.webp", text: "" },
  { image: "/gallery/optimized/gallery-04.webp", text: "" },
  { image: "/gallery/optimized/gallery-05.webp", text: "" },
  { image: "/gallery/optimized/gallery-06.webp", text: "" },
  { image: "/gallery/optimized/gallery-07.webp", text: "" },
  { image: "/gallery/optimized/gallery-08.webp", text: "" },
  { image: "/gallery/optimized/gallery-09.webp", text: "" },
  { image: "/gallery/optimized/gallery-10.webp", text: "" },
  { image: "/gallery/optimized/gallery-11.webp", text: "" },
  { image: "/gallery/optimized/gallery-12.webp", text: "" },
  { image: "/gallery/optimized/gallery-13.webp", text: "" },
  { image: "/gallery/optimized/gallery-14.webp", text: "" },
];
